name: Continous Integration

on:
  workflow_dispatch:
  push:

jobs:
  Build_React:
    runs-on: ubuntu-latest
    steps:
      - name: Install Actions for GitHub
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install All Dev/Dependencies
        run: |
          npm install
      - name: Building Application
        run: |
          npm run build
          date >> last_update.txt
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: save_ci_action_commit
          
  Deploy_Page:
    runs-on: ubuntu-latest
    needs: [Build_React]
    steps:
      - name: Install Actions for GitHub
        uses: actions/checkout@v3
      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
